app = "wireguard-vpn"

primary_region = "gru"

[build]
  image = "docker.io/linuxserver/wireguard"

[env]
  PUID = "1000"
  PGID = "1000"
  TZ = "America/Sao_Paulo"
  SERVERURL = "wireguard-vpn.fly.dev"  # Pode deixar o host da sua app
  SERVERPORT = "51820"
  PEERS = "1"
  PEERDNS = "1.1.1.1"
  INTERNAL_SUBNET = "10.13.13.0"
  ALLOWEDIPS = "0.0.0.0/0"
  LOG_CONFS = "true"

[[services]]
  internal_port = 51820
  protocol = "udp"

  [[services.ports]]
    port = 51820
    handlers = ["udp"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
